### ISSUE TITLE
Windows and Ubuntu Running 11ty

### ISSUE THREAD

**Issue by Stedag** [dendronhq/dendron-11ty#7]
# Context

Implementation of publish V2

# Cases
1)
Windows 10
Dendron-cli: 0.21.0
Dendron-11ty: 1.3.1
-It appeared that a an asset was missing from the Dendron-cli

2)
Ubuntu 20.04
Node 12.18.2
Dendron-cli: 0.21.0
Dendron-11ty: 1.3.3
Error due to config for Eleventy

3)
Windows Server 2019
Node 14.15.3.
Unspecified Error

I might add further cases and the actual stacktraces. If they come up again.

**Comment by kevinslin** [comment]
This should be fixed now. Can you confirm @Stedag ?

**Comment by Stedag** [comment]
Confirmed 👍
